spring.profiles.active=local

###### Email Properties ######
#smtp mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tomasnikolov12@gmail.com
spring.mail.password=znlhjkslesrqgpdo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true